spring:
    application:
        name: hlxy-admin
    boot:
      admin:
        turbine:
          #clusters: default
          url: http://hlxy-hystrix:3555/turbine.stream
server:
  port: 3444

eureka:
  instance:
    hostname: hlxy-admin
   # prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://hlxy-eureka:3000/eureka/





