spring:
    application:
        name: hlxy-user
    zipkin:
        base-url: http://hlxy-sleuth:3666/
        enabled: true
server:
  port: 3333

eureka:
  instance:
    hostname: hlxy-user
  client:
    serviceUrl:
      defaultZone: http://hlxy-eureka:3000/eureka/



