hlxy-eureka:
  image: dh/hlxy-eureka
  ports:
   - "3000:3000"
  hostname: hlxy-eureka

hlxy-api:
  image: dh/hlxy-api
  ports:
   - "3111:3111"
  hostname: hlxy-api
  links:
   - 'hlxy-eureka'
   - 'hlxy-user'
   - 'hlxy-order'
   - 'hlxy-sleuth'
hlxy-user:
  image: dh/hlxy-user
  hostname: hlxy-user
  ports:
   - "3333:3333"
  links:
   - 'hlxy-eureka'
   - 'hlxy-sleuth'

hlxy-order:
  image: dh/hlxy-order
  ports:
   - "3334:3334"
  hostname: hlxy-order
  links:
   - 'hlxy-eureka'
   - 'hlxy-sleuth'

#hlxy-order2:
#  image: dh/hlxy-order
#  ports:
#   - "3335:3334"
#  hostname: hlxy-order2
#  links:
#   - 'hlxy-eureka'
#
hlxy-admin:
  image: dh/hlxy-admin
  ports:
   - "3444:3444"
  hostname: hlxy-admin
  links:
   - 'hlxy-eureka'
   - 'hlxy-user'
   - 'hlxy-order'
   - 'hlxy-api'
   - 'hlxy-hystrix'
   - 'hlxy-sleuth'

hlxy-hystrix:
  image: dh/hlxy-hystrix
  ports:
   - "3555:3555"
  hostname: hlxy-hystrix
  links:
   - 'hlxy-eureka'
   - 'hlxy-user'
   - 'hlxy-order'
   - 'hlxy-api'
   - 'hlxy-sleuth'
hlxy-sleuth:
  image: dh/hlxy-sleuth
  ports:
   - "3666:3666"
  hostname: hlxy-sleuth
  links:
   - 'hlxy-eureka'
   - 'hlxy-user'
   - 'hlxy-order'
   - 'hlxy-api'
#   - 'hlxy-rabbitmq'
#hlxy-rabbitmq:
#  image: registry.cn-hangzhou.aliyuncs.com/peachyy/rabbitmq:3.6.5
#  ports:
#   - "15672:15672"
#   - "5672:5672"
#   - "5671:5671"
#  hostname: hlxy-rabbitmq