hlxy-eureka:
  image: dh/hlxy-eureka
  ports:
   - "3000:3000"
  hostname: hlxy-eureka

hlxy-api:
  image: dh/hlxy-api
  ports:
   - "3111:3111"
  hostname: hlxy-api
  links:
   - 'hlxy-eureka'
   - 'hlxy-user'
   - 'hlxy-order'
   - 'hlxy-order2'
hlxy-user:
  image: dh/hlxy-user
  hostname: hlxy-user
  ports:
   - "3333:3333"
  links:
   - 'hlxy-eureka'

hlxy-order:
  image: dh/hlxy-order
  ports:
   - "3334:3334"
  hostname: hlxy-order
  links:
   - 'hlxy-eureka'

hlxy-order2:
  image: dh/hlxy-order
  ports:
   - "3335:3334"
  hostname: hlxy-order2
  links:
   - 'hlxy-eureka'
#
hlxy-admin:
  image: dh/hlxy-admin
  ports:
   - "3444:3444"
  hostname: hlxy-admin
  links:
   - 'hlxy-eureka'
   - 'hlxy-user'
   - 'hlxy-order'
   - 'hlxy-api'
   - 'hlxy-order2'