spring:
    application:
        name: hlxy-order
    zipkin:
        base-url: http://hlxy-sleuth:3666/
        enabled: true

server:
  port: 3334

eureka:
  instance:
    #hostname: hlxy-order
  client:
    serviceUrl:
      defaultZone: http://hlxy-eureka:3000/eureka/


