spring:
    application:
        name: hlxy-api
    cloud:
    #负载均衡
      loadbalancer:
        retry:
          enabled: true

server:
  port: 3111

eureka:
  instance:
    hostname: hlxy-api
  client:
    serviceUrl:
      defaultZone: http://hlxy-eureka:3000/eureka/

#zuul相关

zuul:
  routes:
    user:
      path: /user/**
      service-id: hlxy-user
    order:
      path: /order/**
      service-id: hlxy-order
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
