spring:
    application:
        name: hlxy-eureka

server:
  port: 3000

eureka:
  instance:
    hostname: hlxy-eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/