spring:
    application:
        name: hlxy-hystrix
    cloud:
    #负载均衡
      loadbalancer:
        retry:
          enabled: true

server:
  port: 3555


eureka:
  instance:
    hostname: hlxy-hystrix
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://hlxy-eureka:3000/eureka/

turbine:
 # aggregator:
 #   clusterConfig: MAIN
  appConfig: hlxy-user,hlxy-order
  #clusterNameExpression: metadata['cluster']
  clusterNameExpression: new String('default')
  combineHostPort: true
  InstanceMonitor:
    eventStream:
      skipLineLogic:
        enabled: false