spring:
    application:
        name: hlxy-sleuth



server:
  port: 3666

eureka:
  instance:
    hostname: hlxy-sleuth
  client:
    serviceUrl:
      defaultZone: http://hlxy-eureka:3000/eureka/




